{{- if .Values.configMaps.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "secret.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
  annotations:
    kubed.appscode.com/sync: ""
data:
{{- range $key, $val := .Values.configMaps.configurations }}
  {{ $key }}: |-
    {{- include "secret.tplvalues.render" (dict "value" $val "context" $) | nindent 4 }}
{{- end }}

{{- end }}
