apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.name" . }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
    annotations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{- if $val -}}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
  {{- end}}

spec:
  selector:
    {{- include "secret.selectorLabels" . | nindent 4 }}