apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
  annotations:
    kubed.appscode.com/sync: ""
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{- if $val }}
  {{ $key }}: {{ $val | toString | b64enc}}
  {{- end}}
  {{- end}}