{{- if .Values.ingress.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "service.tlsSecretName" $ }}
  namespace: cert-manager
spec:
  secretName: {{ template "service.tlsSecretName" $ }}
  issuerRef:
    name: {{ $.Values.ingress.certManager.issuerRef }}
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: ''
  dnsNames:
  {{- range $host := .Values.ingress.certManager.hosts }}
    - {{ $host }}
  {{- end }}
{{- end }}