{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- range $ingressHost := .Values.ingress.hosts }}
    - host: {{ $ingressHost }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $.Values.service.name }}
              servicePort: {{ $.Values.service.port }}
  {{- end }}
  {{- if .Values.ingress.certManager.enabled }}
  tls:
  {{- range $h := .Values.ingress.certManager.hosts }}
    - host: {{ $h }}
      secretName: {{ template "service.tlsSecretName" $ }}
  {{- end }}
  {{- end }}
{{- end }}
