{{- if and .Values.env.enable .Values.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.secretName" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end}}